// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: internal/proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SwiftAgent_DefineVM_FullMethodName    = "/swift.agent.v1.SwiftAgent/DefineVM"
	SwiftAgent_DeleteVM_FullMethodName    = "/swift.agent.v1.SwiftAgent/DeleteVM"
	SwiftAgent_StartVM_FullMethodName     = "/swift.agent.v1.SwiftAgent/StartVM"
	SwiftAgent_StopVM_FullMethodName      = "/swift.agent.v1.SwiftAgent/StopVM"
	SwiftAgent_RebootVM_FullMethodName    = "/swift.agent.v1.SwiftAgent/RebootVM"
	SwiftAgent_ListVMs_FullMethodName     = "/swift.agent.v1.SwiftAgent/ListVMs"
	SwiftAgent_GetVM_FullMethodName       = "/swift.agent.v1.SwiftAgent/GetVM"
	SwiftAgent_GetVMXML_FullMethodName    = "/swift.agent.v1.SwiftAgent/GetVMXML"
	SwiftAgent_PlaceVM_FullMethodName     = "/swift.agent.v1.SwiftAgent/PlaceVM"
	SwiftAgent_GetHostInfo_FullMethodName = "/swift.agent.v1.SwiftAgent/GetHostInfo"
	SwiftAgent_WatchHealth_FullMethodName = "/swift.agent.v1.SwiftAgent/WatchHealth"
	SwiftAgent_PullImage_FullMethodName   = "/swift.agent.v1.SwiftAgent/PullImage"
	SwiftAgent_CacheStatus_FullMethodName = "/swift.agent.v1.SwiftAgent/CacheStatus"
)

// SwiftAgentClient is the client API for SwiftAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwiftAgentClient interface {
	// VM Lifecycle
	DefineVM(ctx context.Context, in *DefineVMRequest, opts ...grpc.CallOption) (*DefineVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	RebootVM(ctx context.Context, in *RebootVMRequest, opts ...grpc.CallOption) (*RebootVMResponse, error)
	// VM Queries
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	GetVMXML(ctx context.Context, in *GetVMXMLRequest, opts ...grpc.CallOption) (*GetVMXMLResponse, error)
	// Placement — agent evaluates resources and returns placement decision
	PlaceVM(ctx context.Context, in *PlaceVMRequest, opts ...grpc.CallOption) (*PlaceVMResponse, error)
	// Health & Resources
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*HostInfo, error)
	WatchHealth(ctx context.Context, opts ...grpc.CallOption) (SwiftAgent_WatchHealthClient, error)
	// Image Cache — agent pulls images from URLs
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (SwiftAgent_PullImageClient, error)
	CacheStatus(ctx context.Context, in *CacheStatusRequest, opts ...grpc.CallOption) (*CacheStatusResponse, error)
}

type swiftAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSwiftAgentClient(cc grpc.ClientConnInterface) SwiftAgentClient {
	return &swiftAgentClient{cc}
}

func (c *swiftAgentClient) DefineVM(ctx context.Context, in *DefineVMRequest, opts ...grpc.CallOption) (*DefineVMResponse, error) {
	out := new(DefineVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_DefineVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_DeleteVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	out := new(StartVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_StartVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	out := new(StopVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_StopVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) RebootVM(ctx context.Context, in *RebootVMRequest, opts ...grpc.CallOption) (*RebootVMResponse, error) {
	out := new(RebootVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_RebootVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_ListVMs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_GetVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) GetVMXML(ctx context.Context, in *GetVMXMLRequest, opts ...grpc.CallOption) (*GetVMXMLResponse, error) {
	out := new(GetVMXMLResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_GetVMXML_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) PlaceVM(ctx context.Context, in *PlaceVMRequest, opts ...grpc.CallOption) (*PlaceVMResponse, error) {
	out := new(PlaceVMResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_PlaceVM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*HostInfo, error) {
	out := new(HostInfo)
	err := c.cc.Invoke(ctx, SwiftAgent_GetHostInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swiftAgentClient) WatchHealth(ctx context.Context, opts ...grpc.CallOption) (SwiftAgent_WatchHealthClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwiftAgent_ServiceDesc.Streams[0], SwiftAgent_WatchHealth_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &swiftAgentWatchHealthClient{stream}
	return x, nil
}

type SwiftAgent_WatchHealthClient interface {
	Send(*HealthPing) error
	Recv() (*HealthEvent, error)
	grpc.ClientStream
}

type swiftAgentWatchHealthClient struct {
	grpc.ClientStream
}

func (x *swiftAgentWatchHealthClient) Send(m *HealthPing) error {
	return x.ClientStream.SendMsg(m)
}

func (x *swiftAgentWatchHealthClient) Recv() (*HealthEvent, error) {
	m := new(HealthEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *swiftAgentClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (SwiftAgent_PullImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwiftAgent_ServiceDesc.Streams[1], SwiftAgent_PullImage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &swiftAgentPullImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SwiftAgent_PullImageClient interface {
	Recv() (*PullImageProgress, error)
	grpc.ClientStream
}

type swiftAgentPullImageClient struct {
	grpc.ClientStream
}

func (x *swiftAgentPullImageClient) Recv() (*PullImageProgress, error) {
	m := new(PullImageProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *swiftAgentClient) CacheStatus(ctx context.Context, in *CacheStatusRequest, opts ...grpc.CallOption) (*CacheStatusResponse, error) {
	out := new(CacheStatusResponse)
	err := c.cc.Invoke(ctx, SwiftAgent_CacheStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwiftAgentServer is the server API for SwiftAgent service.
// All implementations must embed UnimplementedSwiftAgentServer
// for forward compatibility
type SwiftAgentServer interface {
	// VM Lifecycle
	DefineVM(context.Context, *DefineVMRequest) (*DefineVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	RebootVM(context.Context, *RebootVMRequest) (*RebootVMResponse, error)
	// VM Queries
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	GetVMXML(context.Context, *GetVMXMLRequest) (*GetVMXMLResponse, error)
	// Placement — agent evaluates resources and returns placement decision
	PlaceVM(context.Context, *PlaceVMRequest) (*PlaceVMResponse, error)
	// Health & Resources
	GetHostInfo(context.Context, *GetHostInfoRequest) (*HostInfo, error)
	WatchHealth(SwiftAgent_WatchHealthServer) error
	// Image Cache — agent pulls images from URLs
	PullImage(*PullImageRequest, SwiftAgent_PullImageServer) error
	CacheStatus(context.Context, *CacheStatusRequest) (*CacheStatusResponse, error)
	mustEmbedUnimplementedSwiftAgentServer()
}

// UnimplementedSwiftAgentServer must be embedded to have forward compatible implementations.
type UnimplementedSwiftAgentServer struct {
}

func (UnimplementedSwiftAgentServer) DefineVM(context.Context, *DefineVMRequest) (*DefineVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefineVM not implemented")
}
func (UnimplementedSwiftAgentServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedSwiftAgentServer) StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedSwiftAgentServer) StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedSwiftAgentServer) RebootVM(context.Context, *RebootVMRequest) (*RebootVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebootVM not implemented")
}
func (UnimplementedSwiftAgentServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedSwiftAgentServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedSwiftAgentServer) GetVMXML(context.Context, *GetVMXMLRequest) (*GetVMXMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMXML not implemented")
}
func (UnimplementedSwiftAgentServer) PlaceVM(context.Context, *PlaceVMRequest) (*PlaceVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceVM not implemented")
}
func (UnimplementedSwiftAgentServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*HostInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedSwiftAgentServer) WatchHealth(SwiftAgent_WatchHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchHealth not implemented")
}
func (UnimplementedSwiftAgentServer) PullImage(*PullImageRequest, SwiftAgent_PullImageServer) error {
	return status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedSwiftAgentServer) CacheStatus(context.Context, *CacheStatusRequest) (*CacheStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CacheStatus not implemented")
}
func (UnimplementedSwiftAgentServer) mustEmbedUnimplementedSwiftAgentServer() {}

// UnsafeSwiftAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwiftAgentServer will
// result in compilation errors.
type UnsafeSwiftAgentServer interface {
	mustEmbedUnimplementedSwiftAgentServer()
}

func RegisterSwiftAgentServer(s grpc.ServiceRegistrar, srv SwiftAgentServer) {
	s.RegisterService(&SwiftAgent_ServiceDesc, srv)
}

func _SwiftAgent_DefineVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefineVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).DefineVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_DefineVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).DefineVM(ctx, req.(*DefineVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_RebootVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).RebootVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_RebootVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).RebootVM(ctx, req.(*RebootVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_GetVMXML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMXMLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).GetVMXML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_GetVMXML_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).GetVMXML(ctx, req.(*GetVMXMLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_PlaceVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).PlaceVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_PlaceVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).PlaceVM(ctx, req.(*PlaceVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwiftAgent_WatchHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwiftAgentServer).WatchHealth(&swiftAgentWatchHealthServer{stream})
}

type SwiftAgent_WatchHealthServer interface {
	Send(*HealthEvent) error
	Recv() (*HealthPing, error)
	grpc.ServerStream
}

type swiftAgentWatchHealthServer struct {
	grpc.ServerStream
}

func (x *swiftAgentWatchHealthServer) Send(m *HealthEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *swiftAgentWatchHealthServer) Recv() (*HealthPing, error) {
	m := new(HealthPing)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SwiftAgent_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwiftAgentServer).PullImage(m, &swiftAgentPullImageServer{stream})
}

type SwiftAgent_PullImageServer interface {
	Send(*PullImageProgress) error
	grpc.ServerStream
}

type swiftAgentPullImageServer struct {
	grpc.ServerStream
}

func (x *swiftAgentPullImageServer) Send(m *PullImageProgress) error {
	return x.ServerStream.SendMsg(m)
}

func _SwiftAgent_CacheStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwiftAgentServer).CacheStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwiftAgent_CacheStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwiftAgentServer).CacheStatus(ctx, req.(*CacheStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwiftAgent_ServiceDesc is the grpc.ServiceDesc for SwiftAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwiftAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swift.agent.v1.SwiftAgent",
	HandlerType: (*SwiftAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DefineVM",
			Handler:    _SwiftAgent_DefineVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _SwiftAgent_DeleteVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _SwiftAgent_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _SwiftAgent_StopVM_Handler,
		},
		{
			MethodName: "RebootVM",
			Handler:    _SwiftAgent_RebootVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _SwiftAgent_ListVMs_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _SwiftAgent_GetVM_Handler,
		},
		{
			MethodName: "GetVMXML",
			Handler:    _SwiftAgent_GetVMXML_Handler,
		},
		{
			MethodName: "PlaceVM",
			Handler:    _SwiftAgent_PlaceVM_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _SwiftAgent_GetHostInfo_Handler,
		},
		{
			MethodName: "CacheStatus",
			Handler:    _SwiftAgent_CacheStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHealth",
			Handler:       _SwiftAgent_WatchHealth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullImage",
			Handler:       _SwiftAgent_PullImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/agent.proto",
}
