
on:
  push:
      # Sequence of patterns matched against refs/tags
      branches: [ test ]
      #tags:
      #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Build Release
jobs:
  release-unix:
    name: release unix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Add Libvirt-dev lib
        run: sudo apt install qemu-kvm libvirt-daemon-system libvirt-dev -y
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          builds:
            - id: linux-build
              goos:
                - linux
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_FILES: "LICENSE"
